data_args:
  show_raw_preds: True
  buffer_size: 100000 # for shuffling in dataloader
  data_seed: 42
  shuffle_train: True
  dataset_for_choosing_best_model: "VGWD"
  datasets:
    VGWD:
      train_path: "data/vgwd/train.jsonl"
      valid_path: "data/vgwd/valid.jsonl"
      weight: 1.0
      # smoke test라서 일부만 사용
      limit_train_split: 100
      limit_val_split: 16
      limit_example_split: 2

      source_token: "<nist>"

preprocess_args:
  log_base: 1.28
  log_shift: 29

model_args:
  tokenizer_path: "tokenizer/tokenizer_mf10M.model"
  decoder_seq_len: 200
  max_mz: 500               # controls vocab size for encoder, if separate_encoder_decoder_embeds=True
  separate_encoder_decoder_embeds: True
  encoder_layers: 12
  encoder_ffn_dim: 4096
  encoder_attention_heads: 16
  decoder_layers: 12
  decoder_ffn_dim: 4096
  decoder_attention_heads: 16


example_generation_args:
  "top_k": null
  "top_p": null
  "do_sample": True
  "num_beams": 5
  "temperature": null
  "penalty_alpha": null
  "num_return_sequences": 1  # NEVER TOUCH THIS
  "length_penalty": 1.0      # (use for beam search otherwise set to 0)


hf_training_args:
  do_train: True
  do_eval: True

  # -----------------------------
  # Smoke test
  # -----------------------------
  max_steps: 20
  optim: "adamw_torch"
  warmup_steps: 2

  # LoRA 학습률
  learning_rate: 0.0001

  # -----------------------------
  # RTX 3070 8GB
  # 자동 batch size 사용 금지
  # -----------------------------
  auto_bs: False

  per_device_train_batch_size: 1
  per_device_eval_batch_size: 2

  gradient_accumulation_steps: 4
  eval_accumulation_steps: 1

  dataloader_num_workers: 2
  dataloader_drop_last: False

  # smoke test에서는 wandb 사용 안 함
  report_to: "none"

  remove_unused_columns: False
  logging_steps: 1

  fp16: True
  seed: 42

  predict_with_generate: True
  generation_num_beams: 1
  generation_max_length: 200

  # -----------------------------
  # 10 step마다 validation
  # -----------------------------
  evaluation_strategy: "steps"
  eval_steps: 10

  # -----------------------------
  # 10 step마다 checkpoint
  # -----------------------------
  save_steps: 10
  save_strategy: "steps"
  save_total_limit: 2

  load_best_model_at_end: True

  metric_for_best_model: "eval_morgan_tanimoto_simil"
  greater_is_better: True
