general:
  device: cuda
  additional_naming_info: "beam10_clean_lora"

dataset:
  data_path: "data/vgwd_clean/test.jsonl"
  dataset_name: VGWD
  data_split: test

dataloader:
  batch_size: 1
  num_workers: 1

tokenizer_path: "tokenizer/tokenizer_mf10M.model"

generation_args:
  "top_k": null
  "top_p": null
  "do_sample": False
  "num_beams": 10
  "temperature": null
  "penalty_alpha": null
  "num_return_sequences": 10
  "max_length": 200
  "decoder_input_token": "<nist>"
  "length_penalty": 1.0

preprocess_args:
  "source_token": "<nist>"
  "restrict_intensities": False
  "inference_mode": True
  "max_num_peaks": 300
  "max_mol_repr_len": 100
  "max_mz": 500
  "mol_repr": "smiles"
  "log_base": 1.28
  "log_shift": 29
  "max_cumsum": null